"""create_user_tables

Revision ID: 19fc71ce756a
Revises: 
Create Date: 2025-04-20 12:20:44.346914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19fc71ce756a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university_members',
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('enrollment', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('fullname', sa.String(length=64), nullable=False),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('father_name', sa.String(length=64), nullable=True),
    sa.Column('mother_name', sa.String(length=64), nullable=True),
    sa.Column('responsible', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_university_members_created_at'), 'university_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_university_members_email'), 'university_members', ['email'], unique=False)
    op.create_index(op.f('ix_university_members_updated_at'), 'university_members', ['updated_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('PROFESSOR', 'COORDINATOR', 'ADMIN', 'STUDENT', 'RESPONSIBLE', name='roleenum'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_university_members_updated_at'), table_name='university_members')
    op.drop_index(op.f('ix_university_members_email'), table_name='university_members')
    op.drop_index(op.f('ix_university_members_created_at'), table_name='university_members')
    op.drop_table('university_members')
    # ### end Alembic commands ###
