"""add on delete constraint on user profile constraint

Revision ID: 3cb8a3d1e2cf
Revises: dc152ec75f49
Create Date: 2025-04-27 15:27:58.786754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb8a3d1e2cf'
down_revision: Union[str, None] = 'dc152ec75f49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_profile_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_profile_id_fkey', 'users', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###
