"""remove_email_column_on_profile_table

Revision ID: bb84b12a88b2
Revises: ea9f86fdcadd
Create Date: 2025-04-26 17:22:05.154343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb84b12a88b2'
down_revision: Union[str, None] = 'ea9f86fdcadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profiles_email', table_name='profiles')
    op.drop_column('profiles', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index('ix_profiles_email', 'profiles', ['email'], unique=False)
    # ### end Alembic commands ###
