"""adjust_cpf_and_phone_on_profile_table

Revision ID: dc152ec75f49
Revises: bb84b12a88b2
Create Date: 2025-04-26 17:42:06.972635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc152ec75f49'
down_revision: Union[str, None] = 'bb84b12a88b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=11),
               existing_nullable=False)
    op.alter_column('profiles', 'phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=11),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'phone',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('profiles', 'cpf',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    # ### end Alembic commands ###
