"""create frequencies

Revision ID: 2cd854f0c9e6
Revises: 9b48aee84b5f
Create Date: 2025-04-21 02:41:53.899089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd854f0c9e6'
down_revision: Union[str, None] = '9b48aee84b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequencies',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('discipline_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frequencies_archived'), 'frequencies', ['archived'], unique=False)
    op.create_index(op.f('ix_frequencies_date'), 'frequencies', ['date'], unique=False)
    op.create_index(op.f('ix_frequencies_deleted'), 'frequencies', ['deleted'], unique=False)
    op.create_table('frequencies_students',
    sa.Column('frequency_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['frequency_id'], ['frequencies.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequencies_students')
    op.drop_index(op.f('ix_frequencies_deleted'), table_name='frequencies')
    op.drop_index(op.f('ix_frequencies_date'), table_name='frequencies')
    op.drop_index(op.f('ix_frequencies_archived'), table_name='frequencies')
    op.drop_table('frequencies')
    # ### end Alembic commands ###
