"""add activity in exam

Revision ID: 415061317326
Revises: 6438c5cd9933
Create Date: 2025-05-01 14:26:55.040358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415061317326'
down_revision: Union[str, None] = '6438c5cd9933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('activity_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'exams', 'activities', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_column('exams', 'activity_id')
    # ### end Alembic commands ###
