"""create user relationship as student and teacher

Revision ID: 4de9c5cbb03f
Revises: 2cd854f0c9e6
Create Date: 2025-04-21 15:37:53.111048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4de9c5cbb03f'
down_revision: Union[str, None] = '2cd854f0c9e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('student_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('professor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'professors', ['professor_id'], ['id'])
    op.create_foreign_key(None, 'users', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'professor_id')
    op.drop_column('users', 'student_id')
    # ### end Alembic commands ###
