"""create classrooms

Revision ID: 5de61cefcb4e
Revises: 621cf6cee702
Create Date: 2025-04-19 23:02:47.547099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de61cefcb4e'
down_revision: Union[str, None] = '621cf6cee702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('shift', sa.Enum('MORNING', 'AFTERNOON', 'NIGHT', name='shiftenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classrooms_archived'), 'classrooms', ['archived'], unique=False)
    op.create_index(op.f('ix_classrooms_deleted'), 'classrooms', ['deleted'], unique=False)
    op.create_index(op.f('ix_classrooms_name'), 'classrooms', ['name'], unique=False)
    op.create_index(op.f('ix_classrooms_shift'), 'classrooms', ['shift'], unique=False)
    op.add_column('students', sa.Column('classroom_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'students', 'classrooms', ['classroom_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'classroom_id')
    op.drop_index(op.f('ix_classrooms_shift'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_name'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_deleted'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_archived'), table_name='classrooms')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
