"""create disciplines

Revision ID: 9b48aee84b5f
Revises: 5de61cefcb4e
Create Date: 2025-04-20 11:27:21.750958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b48aee84b5f'
down_revision: Union[str, None] = '5de61cefcb4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplines',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('professor_id', sa.UUID(), nullable=True),
    sa.Column('classroom_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplines_archived'), 'disciplines', ['archived'], unique=False)
    op.create_index(op.f('ix_disciplines_deleted'), 'disciplines', ['deleted'], unique=False)
    op.create_index(op.f('ix_disciplines_name'), 'disciplines', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disciplines_name'), table_name='disciplines')
    op.drop_index(op.f('ix_disciplines_deleted'), table_name='disciplines')
    op.drop_index(op.f('ix_disciplines_archived'), table_name='disciplines')
    op.drop_table('disciplines')
    # ### end Alembic commands ###
