"""create activities

Revision ID: 9fb5f2b76229
Revises: 4de9c5cbb03f
Create Date: 2025-04-22 21:39:28.252432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb5f2b76229'
down_revision: Union[str, None] = '4de9c5cbb03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_exam', sa.Boolean(), nullable=False),
    sa.Column('professor_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_archived'), 'activities', ['archived'], unique=False)
    op.create_index(op.f('ix_activities_date'), 'activities', ['date'], unique=False)
    op.create_index(op.f('ix_activities_deleted'), 'activities', ['deleted'], unique=False)
    op.create_index(op.f('ix_activities_description'), 'activities', ['description'], unique=False)
    op.create_index(op.f('ix_activities_is_exam'), 'activities', ['is_exam'], unique=False)
    op.create_index(op.f('ix_activities_title'), 'activities', ['title'], unique=False)
    op.create_table('activities_disciplines',
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('discipline_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities_disciplines')
    op.drop_index(op.f('ix_activities_title'), table_name='activities')
    op.drop_index(op.f('ix_activities_is_exam'), table_name='activities')
    op.drop_index(op.f('ix_activities_description'), table_name='activities')
    op.drop_index(op.f('ix_activities_deleted'), table_name='activities')
    op.drop_index(op.f('ix_activities_date'), table_name='activities')
    op.drop_index(op.f('ix_activities_archived'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
